# Dependencies
markdown            : redcarpet
highlighter         : pygments

# Permalinks
permalink           : pretty
relative_permalinks : true

# Setup
title       : Oguzhan Selcuk
tagline     : ''
description : 'Under Construction'
url         : oselcuk.com
baseurl     : ''

author:
name                : 'Oguzhan Selcuk'
url                 : oselcuk.github.io

paginate            : 5
paginate_path       : "blog/page:num"